version: '2'
services:
   logstash:
     image: docker.elastic.co/logstash/logstash:5.4.0
     environment:
       - PATH_CONFIG=/usr/share/logstash/pipeline/*.conf
     volumes:
       - $PWD/pipeline/:/usr/share/logstash/pipeline/
       - $PWD/data/:/data/
     depends_on:
       - elasticsearch

   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
     ports:
       - "9200:9200"

   kibana:
     image: docker.elastic.co/kibana/kibana:5.4.0
     depends_on:
       - elasticsearch
     environment:
       ELASTICSEARCH_URL: http://elasticsearch:9200
     ports:
       - "5601:5601"


