version: '3'
services:
   logstash:
     image: docker.elastic.co/logstash/logstash:5.6.3
     environment:
       - PATH_CONFIG=/usr/share/logstash/pipeline/*.conf
     volumes:
       - $PWD/pipeline/:/usr/share/logstash/pipeline/
       - $PWD/data/:/data/
       - $PWD/etc/logstash.yml:/usr/share/logstash/config/logstash.yml
     depends_on:
       - elasticsearch

   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
     ports:
       - "9200:9200"
     volumes:
       - $PWD/etc/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

   kibana:
     image: docker.elastic.co/kibana/kibana:5.6.3
     depends_on:
       - elasticsearch
     environment:
       ELASTICSEARCH_URL: http://elasticsearch:9200
     ports:
       - "5601:5601"
     volumes:
       - $PWD/etc/kibana.yml:/usr/share/kibana/config/kibana.yml


